#!/bin/ash /etc/rc.common

START=49
USE_PROCD=1
DEPEND=fstab
PROG=/mnt/UDISK/bin/beacon_usb_bridge

start_service() {
    rm -f /dev/cartographer
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 5
    procd_set_param pidfile /var/run/beacon_usb_bridge.pid
    procd_close_instance
}

stop_service() {
    rm -f /dev/cartographer
}

reload_service() {
    stop
    sleep 2
    start
}
